#!/bin/sh
# File generated by ocamlbuild

cd /home/mdali/OCaml-Work/Documentations/hello_world

rm -f hello.cmi
rm -f hello.cmo
# Also clean the script itself
rm -f /home/mdali/OCaml-Work/Documentations/hello_world/_build/sanitize.sh
